# $ kubectl create configmap codeclimate-cppcheck-config --from-file=config.json

apiVersion: batch/v1
kind: Job
metadata:
  name: s2-cppcheck-parallelism
spec:
  parallelism: 2
  completions: 2
  template:
    spec:
      containers:
      - name: cppcheck
        image: uhziel/codeclimate-cppcheck:0.0.2
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        env:
          - name: CODE_ANALYSIS_WORK_QUEUE_URL
            value: redis
          - name: CODE_ANALYSIS_WORK_QUEUE_NAME
            value: codecheck-jobs
        volumeMounts:
          - mountPath: /code
            name: code
            readOnly: true
          - mountPath: /config.json
            name: config
            readOnly: true
            subPath: config.json
      restartPolicy: Never
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: s2-clone-repo
        - name: config
          configMap:
            name: codeclimate-cppcheck-config
