apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-cjson
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
    - hard
    - nocto
  nfs:
    path: /srv/nfs4/homes/cJSON
    server: 192.168.7.138
