apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
