apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-clone-repo
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
