apiVersion: batch/v1
kind: Job
metadata:
  name: s3-cppcheck-parallelism
spec:
  parallelism: 28
  completions: 28
  template:
    spec:
      containers:
        - name: cppcheck
          image: uhziel/codeclimate-cppcheck:0.0.2
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          env:
            - name: CODE_ANALYSIS_WORK_QUEUE_URL
              value: redis
            - name: CODE_ANALYSIS_WORK_QUEUE_NAME
              value: codecheck-jobs
          volumeMounts:
            - mountPath: /code
              name: code
              readOnly: true
            - mountPath: /config.json
              name: config
              readOnly: true
              subPath: config.json
            - mountPath: /config
              name: config
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: code
          nfs:
            path: /home/nfs_shared/pvc-56630a49-0335-4b7d-8138-4bdff9245836_demo-k8s-codecheck_s3-clone-repo
            server: 192.168.7.189
        - name: config
          configMap:
            name: s3-codeclimate-cppcheck-config
